name: Package - ansiblex

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [amd64, arm64]

    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - run: make build-${{ matrix.platform }}
      - uses: actions/upload-artifact@v3
        with:
          name: ansiblex
          path: "dist/*"
