name: Package - getansible

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [amd64, arm64]

    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - run: make build-${{ matrix.platform }}

      - uses: actions/upload-artifact@v4
        with:
          name: getansible-${{ matrix.platform }}
          path: "dist/*"

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - id: prerelease
        run: |
          echo "prerelease=$(if [[ "${{ github.ref }}" == *"-rc"* ]]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          name: getansible-amd64

      - uses: actions/download-artifact@v4
        with:
          name: getansible-arm64

      - uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          files: |
            getansible-amd64
            getansible-arm64
