name: Release - getansible.sh

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        version:
          - ansible_version: 3.0
            python_version: 3.8.19
          - ansible_version: 4.0
            python_version: 3.8.19
          - ansible_version: 5.0
            python_version: 3.8.19
          - ansible_version: 6.0
            python_version: 3.8.19
          - ansible_version: 7.0
            python_version: 3.11.9
          - ansible_version: 8.0
            python_version: 3.11.9
          - ansible_version: 9.0
            python_version: 3.11.9
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - run: make build-${{ matrix.platform }} ANSIBLE_VERSION=${{ matrix.version.ansible_version }} PYTHON_VERSION=${{ matrix.version.python_version }}

      - uses: actions/upload-artifact@v4
        with:
          name: getansible-${{ matrix.platform }}
          path: "dist/*"

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - id: prerelease
        run: |
          echo "prerelease=$(if [[ "${{ github.ref }}" == *"-rc"* ]]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          files: |
            getansible-*
