---
name: Release - getansible.sh

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint shell scripts
        run: |
          sudo apt-get install shellcheck
          shellcheck src/*.sh docs/*.sh

  build-darwin:
    runs-on: macos-latest
    needs: lint

    strategy:
      matrix:
        platform:
          - arm64
        version:
          - ANSIBLE_RELEASE: "9.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "10.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: >-
          make build
          ANSIBLE_RELEASE=${{ matrix.version.ANSIBLE_RELEASE }}
          ANSIBLE_PLATFORM=${{ matrix.platform }}
          PYTHON_VERSION=${{ matrix.version.PYTHON_VERSION }}
          PYTHON_RELEASE=${{ matrix.version.PYTHON_RELEASE }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: getansible-${{ matrix.version.ANSIBLE_RELEASE }}-darwin-${{ matrix.platform }}
          path: "src/dist/*"

  build-linux:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        version:
          - ANSIBLE_RELEASE: "3.0"
            PYTHON_VERSION: "3.8.19"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "4.0"
            PYTHON_VERSION: "3.8.19"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "5.0"
            PYTHON_VERSION: "3.8.19"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "6.0"
            PYTHON_VERSION: "3.8.19"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "7.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "8.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "9.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "10.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: >-
          make build-docker test
          ANSIBLE_RELEASE=${{ matrix.version.ANSIBLE_RELEASE }}
          ANSIBLE_PLATFORM=${{ matrix.platform }}
          PYTHON_VERSION=${{ matrix.version.PYTHON_VERSION }}
          PYTHON_RELEASE=${{ matrix.version.PYTHON_RELEASE }}

      - name: Test
        run: >-
          make build-docker test
          ANSIBLE_RELEASE=${{ matrix.version.ANSIBLE_RELEASE }}
          ANSIBLE_PLATFORM=${{ matrix.platform }}
          PYTHON_VERSION=${{ matrix.version.PYTHON_VERSION }}
          PYTHON_RELEASE=${{ matrix.version.PYTHON_RELEASE }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: getansible-${{ matrix.version.ANSIBLE_RELEASE }}-linux-${{ matrix.platform }}
          path: "src/dist/*"

  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-darwin
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - id: prerelease
        run: |
          echo "prerelease=$(if [[ "${{ github.ref }}" == *"-rc"* ]]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create SHA512SUMS
        run: |
          sha512sum getansible-* > SHA512SUMS

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          files: |
            SHA512SUMS
            getansible-*
