---
name: Release - getansible.sh

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint shell scripts
        run: |
          sudo apt-get install shellcheck
          shellcheck src/*.sh docs/*.sh

  build-darwin:
    runs-on: macos-latest
    needs: lint

    strategy:
      matrix:
        platform:
          - arm64
        version:
          - ANSIBLE_RELEASE: "9.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "10.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: >-
          make build
          ANSIBLE_RELEASE=${{ matrix.version.ANSIBLE_RELEASE }}
          ANSIBLE_PLATFORM=${{ matrix.platform }}
          PYTHON_VERSION=${{ matrix.version.PYTHON_VERSION }}
          PYTHON_RELEASE=${{ matrix.version.PYTHON_RELEASE }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: getansible-${{ matrix.version.ANSIBLE_RELEASE }}-darwin-${{ matrix.platform }}
          path: "src/dist/*"

  smoke-test-darwin:
    runs-on: macos-latest
    needs: build-darwin

    strategy:
      matrix:
        platform:
          - arm64
        version:
          - ANSIBLE_RELEASE: "9.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "10.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: getansible-${{ matrix.version.ANSIBLE_RELEASE }}-darwin-${{ matrix.platform }}

      - name: Smoke Test
        run: |
          chmod +x getansible-${{ matrix.version.ANSIBLE_RELEASE }}-darwin-${{ matrix.platform }}.sh
          ./getansible-${{ matrix.version.ANSIBLE_RELEASE }}-darwin-${{ matrix.platform }}.sh -- ansible --version

  build-linux-amd64:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        platform:
          - amd64
        version:
          - ANSIBLE_RELEASE: "9.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "10.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: >-
          make build
          ANSIBLE_RELEASE=${{ matrix.version.ANSIBLE_RELEASE }}
          ANSIBLE_PLATFORM=${{ matrix.platform }}
          PYTHON_VERSION=${{ matrix.version.PYTHON_VERSION }}
          PYTHON_RELEASE=${{ matrix.version.PYTHON_RELEASE }}

      - name: Smoke Test
        working-directory: src/dist
        run: |
          chmod +x getansible-${{ matrix.version.ANSIBLE_RELEASE }}-linux-${{ matrix.platform }}.sh
          ./getansible-${{ matrix.version.ANSIBLE_RELEASE }}-linux-${{ matrix.platform }}.sh -- ansible --version

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: getansible-${{ matrix.version.ANSIBLE_RELEASE }}-linux-${{ matrix.platform }}
          path: "src/dist/*"

  build-linux-arm64:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        platform:
          - arm64
        version:
          - ANSIBLE_RELEASE: "9.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "10.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: >-
          make build-docker
          ANSIBLE_RELEASE=${{ matrix.version.ANSIBLE_RELEASE }}
          ANSIBLE_PLATFORM=${{ matrix.platform }}
          PYTHON_VERSION=${{ matrix.version.PYTHON_VERSION }}
          PYTHON_RELEASE=${{ matrix.version.PYTHON_RELEASE }}

      - name: Smoke Test
        working-directory: src/dist
        run: |
          chmod +x getansible-${{ matrix.version.ANSIBLE_RELEASE }}-linux-${{ matrix.platform }}.sh
          ./getansible-${{ matrix.version.ANSIBLE_RELEASE }}-linux-${{ matrix.platform }}.sh -- ansible --version

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: getansible-${{ matrix.version.ANSIBLE_RELEASE }}-linux-${{ matrix.platform }}
          path: "src/dist/*"

  test:
    runs-on: ubuntu-latest
    needs: build-linux-amd64

    strategy:
      matrix:
        platform:
          - amd64
        version:
          - ANSIBLE_RELEASE: "9.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"
          - ANSIBLE_RELEASE: "10.0"
            PYTHON_VERSION: "3.11.9"
            PYTHON_RELEASE: "20240415"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: getansible-${{ matrix.version.ANSIBLE_RELEASE }}-linux-${{ matrix.platform }}
          path: src/dist

      - name: Test
        run: >-
          make test
          ANSIBLE_RELEASE=${{ matrix.version.ANSIBLE_RELEASE }}
          ANSIBLE_PLATFORM=${{ matrix.platform }}
          PYTHON_VERSION=${{ matrix.version.PYTHON_VERSION }}
          PYTHON_RELEASE=${{ matrix.version.PYTHON_RELEASE }}

  release:
    runs-on: ubuntu-latest
    needs:
      - build-darwin
      - build-linux-amd64
      - build-linux-arm64
      - test
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - id: prerelease
        run: |
          echo "prerelease=$(if [[ "${{ github.ref }}" == *"-rc"* ]]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create SHA512SUMS
        run: |
          sha512sum getansible-* > SHA512SUMS

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          files: |
            SHA512SUMS
            getansible-*
